✨ feat: Adding a new anti-spam system and refactoring
RustLangES/cangrebot pull request #23
Opened 2024-04-16 18:22 UTC by CrawKatt

I added a new anti-spam system and changed the methods to obtain the username and avatar when generating welcomes to `.face()` and `.distinct()` methods for Nitro users and users who do not have a nickname.

2024-04-16 19:40 UTC, SergioRibera requested changes
Please look the commentaries

2024-04-16 19:40 UTC, SergioRibera commented on Cargo.toml
> +once_cell = "1.18.0"
Personally I don't want to add more dependencies to the project, I would recommend to take a look at this that already comes in the std

https://doc.rust-lang.org/std/cell/struct.LazyCell.html

2024-04-16 19:40 UTC, SergioRibera commented on Cargo.toml
> +chrono = "0.4.31"
Instead of use chrono, look the wrap from serenity

https://docs.rs/serenity/latest/serenity/model/timestamp/struct.Timestamp.html

2024-04-16 19:40 UTC, SergioRibera commented on src/events/anti_spam.rs
> +});
https://doc.rust-lang.org/std/cell/struct.LazyCell.html#examples

2024-04-16 19:40 UTC, SergioRibera commented on src/events/anti_spam.rs
> +    let time = Timestamp::from(Utc::now() + Duration::from_secs(time_out_timer as u64));
I think you can do something like this

```rs
let time = Timestamp::now().unix_timestamp() + (time_out_timer * 1000);
let time = Timestamp::from_unix_timestamp(time)?;
```
With this you don't need chrono as a dependency

https://docs.rs/serenity/latest/serenity/model/timestamp/struct.Timestamp.html#method.now

2024-04-16 20:28 UTC, CrawKatt commented on src/events/anti_spam.rs
> +    let time = Timestamp::from(Utc::now() + Duration::from_secs(time_out_timer as u64));
I tried to use the hint but it returns an Invalid Timestamp error

```
2024-04-16T16:27:33.897-04:00 [Runtime] Error disabling communication Invalid Form Body (communication_disabled_until: Invalid communication disabled timestamp)
```

2024-04-16 20:35 UTC, CrawKatt commented on src/events/anti_spam.rs
> +    let time = Timestamp::from(Utc::now() + Duration::from_secs(time_out_timer as u64));
I solved it, it was not necessary to multiply 1000 to the `time_out_timer` only to add it to `Timestamp::now().unix_timestamp()`.

2024-04-16 20:56 UTC, CrawKatt commented on Cargo.toml
> +once_cell = "1.18.0"
How can I change it? I have been having problems for a while because **threads cannot be safely shared between threads** since `LazyCell` does not implement `Sync`.

2024-04-16 21:16 UTC, SergioRibera commented on Cargo.toml
> +once_cell = "1.18.0"
https://doc.rust-lang.org/std/sync/struct.LazyLock.html

2024-04-16 21:23 UTC, CrawKatt commented on Cargo.toml
> +once_cell = "1.18.0"
Solved

2024-04-16 21:46 UTC, SergioRibera approved these changes

2024-04-20 20:30 UTC, SergioRibera approved these changes

2024-04-21 02:11 UTC, Phosphorus-M approved these changes
Quizas tener en cuenta un sistema a futuro usando directamente reacciones.  
```
Mensaje de bienvenida donde digas reacciona aquí para desbloquear canales ⬇️ 🔽
|324 🦀|
```
Que por defecto solo vea ese canal y al reaccionar gane un rol para ver el resto del server.

2024-04-21 02:16 UTC, SergioRibera commented
> Quizas tener en cuenta un sistema a futuro usando directamente reacciones.
>
Podrias abrir una issue al respecto porfavor para que lo agreguemos al proyecto

2024-04-21 02:36 UTC, CrawKatt commented
> Quizas tener en cuenta un sistema a futuro usando directamente reacciones.
> 
> ```
> Mensaje de bienvenida donde digas reacciona aquí para desbloquear canales ⬇️ 🔽
> |324 🦀|
> ```
> 
> Que por defecto solo vea ese canal y al reaccionar gane un rol para ver el resto del server.

eso suena a un sistema de verificación de miembros por reacción. Creo que puedo hacerlo, he estado trabajando con emojis recientemente

2024-04-27 23:16 UTC, merged